create table cidade (id int8 generated by default as identity, cidade_nome varchar(255) not null, estado int8 not null, primary key (id))
create table cozinha (id int8 generated by default as identity, nome_cozinha varchar(255) not null, primary key (id))
create table estado (id int8 generated by default as identity, estado_nome varchar(255) not null, uf varchar(255) not null, primary key (id))
create table forma_pagamento (id int8 generated by default as identity, descricao varchar(255) not null, primary key (id))
create table grupo (grupo_id int8 generated by default as identity, grupo_nome varchar(255) not null, primary key (grupo_id))
create table grupo_permissao (grupo_id int8 not null, permissao_id int8 not null)
create table permissao (id int8 generated by default as identity, descricao varchar(255) not null, nome varchar(255) not null, primary key (id))
create table produto (produto_id int8 generated by default as identity, produto_descricao varchar(255) not null, produto_ativo boolean not null, produto_nome varchar(255) not null, produto_preco numeric(19, 2) not null, restaurante_id int8 not null, primary key (produto_id))
create table restaurante (id int8 generated by default as identity, data_atualizacao timestamp not null, data_cadastro timestamp not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome_restaurante varchar(150) not null, taxa_frete numeric(19, 2) not null, cozinha_id int8 not null, endereco_cidade int8, primary key (id))
create table restaurante_formas_pagamento (restaurante_id int8 not null, forma_pagamento_id int8 not null)
create table usuario (usuario_id int8 generated by default as identity, usuario_data_cadastro timestamp not null, usuario_email varchar(255) not null, usuario_nome varchar(255) not null, usuario_senha varchar(255) not null, primary key (usuario_id))
create table usuario_grupo (usuario_id int8 not null, grupo_id int8 not null)
alter table if exists cidade add constraint FKedwmmd3jtkssgrwyugrindb7j foreign key (estado) references estado
alter table if exists grupo_permissao add constraint FKh21kiw0y0hxg6birmdf2ef6vy foreign key (permissao_id) references permissao
alter table if exists grupo_permissao add constraint FKta4si8vh3f4jo3bsslvkscc2m foreign key (grupo_id) references grupo
alter table if exists produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante
alter table if exists restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha
alter table if exists restaurante add constraint FKa3ii9yjt0c00jbq7pjxi59jfm foreign key (endereco_cidade) references cidade
alter table if exists restaurante_formas_pagamento add constraint FKg99fjbqkawklm5w9hul267oot foreign key (forma_pagamento_id) references forma_pagamento
alter table if exists restaurante_formas_pagamento add constraint FK7uj3ol5o5h1jpn780cxtl3tvb foreign key (restaurante_id) references restaurante
alter table if exists usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo
alter table if exists usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario
