flyway.url=jdbc:postgresql://localhost:5432/algafood
flyway.user=postgres
flyway.password=postgres

# Comando para execuçaõ via linha de comando:
# $ ./mvnw flyway:repair -Dflyway.configFiles=src/main/resources/flyway.properties