-- V00008__Criação das tabelas Pedido e ItemPedido.sql
CREATE TABLE PEDIDO(
	ID						SERIAL				NOT NULL,
	SUBTOTAL				DECIMAL(18,2)		NOT NULL,
	TAXA_FRETE				DECIMAL(18,2)		NOT NULL,
	VALOR_TOTAL				DECIMAL(18,2)		NOT NULL,
	DATA_CRIACAO			TIMESTAMP			NOT NULL,
	DATA_CONFIRMACAO		TIMESTAMP			NULL,
	DATA_CANCELAMENTO		TIMESTAMP			NULL,
	DATA_ENTREGA			TIMESTAMP			NULL,
	STATUS_PEDIDO			VARCHAR(15)			NOT NULL,
	ENDERECO_LOGRADOURO 	VARCHAR(250) 		NOT NULL,
	ENDERECO_NUMERO 		VARCHAR(10) 		NOT NULL,
	ENDERECO_COMPLEMENTO 	VARCHAR(100) 		NOT NULL,
	ENDERECO_BAIRRO 		VARCHAR(100) 		NOT NULL,
	ENDERECO_CEP 			VARCHAR(10) 		NOT NULL,
	ENDERECO_CIDADE			BIGINT				NOT NULL,
	USUARIO_ID				BIGINT				NOT NULL,
	RESTAURANTE_ID			BIGINT				NOT NULL,
	FORMA_PAGAMENTO_ID		BIGINT				NOT NULL,
	CONSTRAINT PK_PEDIDO
		PRIMARY KEY (ID),
	CONSTRAINT FK_ENDERECO_CIDADE
		FOREIGN KEY (ENDERECO_CIDADE)
			REFERENCES CIDADE(ID),
	CONSTRAINT FK_USUARIO_ID
		FOREIGN KEY (USUARIO_ID)
			REFERENCES USUARIO(USUARIO_ID),
	CONSTRAINT FK_RESTAURANTE_ID
		FOREIGN KEY (RESTAURANTE_ID)
			REFERENCES RESTAURANTE(ID),
	CONSTRAINT FK_FORMA_PAGAMENTO_ID
		FOREIGN KEY (FORMA_PAGAMENTO_ID)
			REFERENCES FORMA_PAGAMENTO(ID)
);

CREATE TABLE ITEM_PEDIDO(
	ID						SERIAL				NOT NULL,
	QUANTIDADE				INTEGER				NOT NULL,
	PRECO_UNITARIO			DECIMAL(18,2)		NOT NULL,
	PRECO_TOTAL				DECIMAL(18,2)		NOT NULL,
	OBSERVACAO				VARCHAR(300)		NULL,
	PEDIDO_ID				BIGINT				NOT NULL,
	PRODUTO_ID				BIGINT				NOT NULL,
	CONSTRAINT PK_ITEM_PEDIDO
		PRIMARY KEY (ID),
	CONSTRAINT FK_PEDIDO_ID
		FOREIGN KEY(PEDIDO_ID)
			REFERENCES PEDIDO(ID),
	CONSTRAINT FK_PRODUTO_ID
		FOREIGN KEY(PRODUTO_ID)
			REFERENCES PRODUTO(PRODUTO_ID)
);