-- V00003__Remove a restrição de not null para endereço
ALTER TABLE RESTAURANTE ALTER COLUMN ENDERECO_LOGRADOURO DROP NOT NULL;
ALTER TABLE RESTAURANTE ALTER COLUMN ENDERECO_NUMERO DROP NOT NULL;
ALTER TABLE RESTAURANTE ALTER COLUMN ENDERECO_COMPLEMENTO DROP NOT NULL; 
ALTER TABLE RESTAURANTE ALTER COLUMN ENDERECO_BAIRRO DROP NOT NULL;
ALTER TABLE RESTAURANTE ALTER COLUMN ENDERECO_CEP DROP NOT NULL;
ALTER TABLE RESTAURANTE ALTER COLUMN ENDERECO_CIDADE DROP NOT NULL;