-- V00010__Permitir complemento de endereço nulo e UK-pedido-produto.sql
ALTER TABLE PEDIDO ALTER COLUMN ENDERECO_COMPLEMENTO DROP NOT NULL;
ALTER TABLE ITEM_PEDIDO ADD CONSTRAINT UK_ITEM_PEDIDO_PRODUTO UNIQUE (PEDIDO_ID, PRODUTO_ID);