
-- Script de migração para criação da base inicial. 
CREATE TABLE COZINHA(
	ID 						SERIAL			NOT NULL,
	NOME_COZINHA 			VARCHAR(200)	NOT NULL,
	COZINHA					BIGINT 			NOT NULL,
	CONSTRAINT PK_COZINHA 
		PRIMARY KEY(ID)
);

CREATE TABLE ESTADO(
	ID 						SERIAL			NOT NULL,
	NOME_ESTADO 			VARCHAR(100)	NOT NULL,
	UF 						VARCHAR(2)		NOT NULL,
	CONSTRAINT PK_ESTADO 
		PRIMARY KEY(ID)
);

CREATE TABLE CIDADE(
	ID 						SERIAL 			NOT NULL,
	NOME_CIDADE 			VARCHAR(100) 	NOT NULL,
	ESTADO 					BIGINT 			NOT NULL,
	CONSTRAINT PK_CIDADE 
		PRIMARY KEY(ID),
	CONSTRAINT FK_CIDADE_ESTADO 
		FOREIGN KEY (ESTADO) 
			REFERENCES ESTADO(ID) 
);

CREATE TABLE RESTAURANTE(
	ID 						SERIAL 			NOT NULL,
	NOME_RESTAURANTE 		VARCHAR(200) 	NOT NULL,
	TAXA_FRETE 				DECIMAL(18,2) 	NOT NULL,
	ENDERECO_LOGRADOURO 	VARCHAR(250) 	NOT NULL,
	ENDERECO_NUMERO 		VARCHAR(10) 	NOT NULL,
	ENDERECO_COMPLEMENTO 	VARCHAR(100) 	NOT NULL,
	ENDERECO_BAIRRO 		VARCHAR(100) 	NOT NULL,
	ENDERECO_CEP 			VARCHAR(10) 	NOT NULL,
	ENDERECO_CIDADE			BIGINT			NOT NULL,
	DATA_CADASTRO			TIMESTAMP		NOT NULL,
	DATA_ATUALIZACAO		TIMESTAMP		NOT NULL,
	COZINHA_ID				BIGINT			NOT NULL,
	CONSTRAINT PK_RESTAURANTE 
		PRIMARY KEY (ID),
	CONSTRAINT FK_RESTAURANTE_CIDADE 
		FOREIGN KEY(ENDERECO_CIDADE) 
			REFERENCES CIDADE(ID),
	CONSTRAINT FK_RESTAURANTE_COZINHA
		FOREIGN KEY (COZINHA_ID)
			REFERENCES COZINHA(ID)
);

CREATE TABLE FORMA_PAGAMENTO(
	ID 						SERIAL			NOT NULL,
	DESCRICAO				VARCHAR(100)	NOT NULL,
	CONSTRAINT PK_FORMA_PAGAMENTO 
		PRIMARY KEY (ID)
);

CREATE TABLE RESTAURANTE_FORMAS_PAGAMENTO(
	RESTAURANTE_ID			BIGINT			NOT NULL,
	FORMA_PAGAMENTO_ID		BIGINT			NOT NULL,
	CONSTRAINT PK_RESTAURANTE_FORMAS_PAGAMENTO 
		PRIMARY KEY (RESTAURANTE_ID,FORMA_PAGAMENTO_ID),
	CONSTRAINT FK_FORMAS_DE_PAGAMENTO_ID_RESTAURANTE
		FOREIGN KEY (RESTAURANTE_ID)
			REFERENCES RESTAURANTE (ID),
	CONSTRAINT FK_FORMAS_DE_PAGAMENTO_ID_FORMA_PAGAMENTO
		FOREIGN KEY (FORMA_PAGAMENTO_ID)
			REFERENCES FORMA_PAGAMENTO (ID)
);

CREATE TABLE PRODUTO(
	PRODUTO_ID				SERIAL			NOT NULL,
	PRODUTO_NOME			VARCHAR(150)	NOT NULL,
	PRODUTO_DESCRICAO		VARCHAR(300)	NOT NULL,
	PRODUTO_PRECO			DECIMAL(18,2)	NOT NULL,
	PRODUTO_ATIVO			BOOLEAN			NOT NULL,
	RESTAURANTE_ID			BIGINT			NOT NULL,
	CONSTRAINT PK_PRODUTO 
		PRIMARY KEY(PRODUTO_ID),
	CONSTRAINT FK_RESTAURANTE
		FOREIGN KEY (RESTAURANTE_ID)
			REFERENCES RESTAURANTE(ID)
);

CREATE TABLE PERMISSAO(
	ID						SERIAL			NOT NULL,
	NOME					VARCHAR(150)	NOT NULL,
	DESCRICAO				VARCHAR(300)	NOT NULL,
	CONSTRAINT PK_PERMISSAO
		PRIMARY KEY (ID)
);

CREATE TABLE GRUPO(
	GRUPO_ID 				SERIAL			NOT NULL,
	GRUPO_NOME				VARCHAR(150)	NOT NULL,
	CONSTRAINT PK_GRUPO 
		PRIMARY KEY (GRUPO_ID)
);

CREATE TABLE GRUPO_PERMISSAO(
	GRUPO_ID				BIGINT			NOT NULL,
	PERMISSSAO_ID			BIGINT			NOT NULL,
	CONSTRAINT PK_GRUPO_PERMISSAO
		PRIMARY KEY (GRUPO_ID, PERMISSSAO_ID),
	CONSTRAINT FK_GRUPO_ID
		FOREIGN KEY (GRUPO_ID)
			REFERENCES GRUPO (GRUPO_ID),
	CONSTRAINT FK_PERMISSAO_ID
		FOREIGN KEY (PERMISSSAO_ID)
			REFERENCES PERMISSAO(ID)
);

CREATE TABLE USUARIO(
	USUARIO_ID 				SERIAL			NOT NULL,
	USUARIO_NOME			VARCHAR(150)	NOT NULL,
	USUARIO_EMAIL			VARCHAR(100)	NOT NULL,
	USUARIO_SENHA			VARCHAR(100)	NOT NULL,
	USUARIO_DATA_CADASTRO	TIMESTAMP		NOT NULL,
	CONSTRAINT PK_USUARIO
		PRIMARY KEY (USUARIO_ID)
);

CREATE TABLE USUARIO_GRUPO(
	USUARIO_ID				BIGINT			NOT NULL,
	GRUPO_ID				BIGINT			NOT NULL,
	CONSTRAINT PK_USUARIO_GRUPO
		PRIMARY KEY (USUARIO_ID, GRUPO_ID),
	CONSTRAINT FK_USUARIO_ID
		FOREIGN KEY (USUARIO_ID)
			REFERENCES USUARIO(USUARIO_ID),
	CONSTRAINT FK_GRUPO_ID
		FOREIGN KEY (GRUPO_ID)
			REFERENCES GRUPO (GRUPO_ID)
);

