-- V00009__Correção no nome da coluna USUARIO_ID para USUARIO_CLIENTE_ID na tabela de pedido.sql
ALTER TABLE PEDIDO RENAME COLUMN USUARIO_ID TO USUARIO_CLIENTE_ID;
ALTER TABLE PEDIDO RENAME CONSTRAINT FK_USUARIO_ID TO FK_USUARIO_CLIENTE_ID;